apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
        - name: profileservice-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/profileservice-ecr-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "DEV"
            - name: SECRET_NAME
              value: ms-profileservice-srv-secret
      imagePullSecrets:
        - name: ecr-key
