apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: dev-appsetting-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dev-appsetting-ecr-repo-cred

