apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-appsetting-deployment
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: qa-appsetting-ecr-repo
          env:
            - name: ENV
              value: "QA"
            - name: SECRET_NAME
              value: ms-appsetting-qasrv-secret
