apiVersion: v1
kind: Service
metadata:
  name: appsetting-service
  namespace: argocd
spec:
  selector:
    app: appsetting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31245
  type: NodePort
