apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsetting-deployment # This must match the name in the base deployment
spec:
  selector:
    matchLabels:
      app: appsetting # Updated matchLabels
  template:
    metadata:
      labels:
        app: appsetting # Updated labels
    spec:
      containers:
        - name: qa-appsetting-ecr-repo # Updated container name
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/qa-appsetting-ecr-repo:latest
          env:
            - name: ENV
              value: "qa"
            - name: SECRET_NAME
              value: ms-appsetting-qasrv-secret
