apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/test1/deployment.yaml
  - ../../base/test1/service.yaml

patches:
  - path: deploy-patch.yaml
    target:
      kind: Deployment
      name: appsetting-deployment
