apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: ms-1-appsetting-patch.yaml
    target:
      kind: Deployment
      name: appsetting-deployment
