apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
  - ms-1-appsetting-patch.yaml
  - ms-2-authservice-patch.yaml
  - ms-3-profileservice-patch.yaml
