apiVersion: v1
kind: Service
metadata:
  name: appsetting-service
spec:
  selector:
    app: appsetting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31351
      name: dev-port
