apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsetting-deployment
spec:
  selector:
    matchLabels:
      app: appsetting
  template:
    metadata:
      labels:
        app: appsetting
    spec:
      containers:
        - name: appsetting-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/qa-appsetting-ecr-repo:latest
          env:
            - name: ENV
              value: "qa"
            - name: SECRET_NAME
              value: ms-appsetting-qasrv-secret
