apiVersion: v1
kind: Service
metadata:
  name: profileservice-service
spec:
  selector:
    app: profileservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31353
      name: dev-port
