apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsetting-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appsetting-deployment
  template:
    metadata:
      labels:
        app: appsetting-deployment
    spec:
      containers:
        - name: appsetting-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/appsetting-ecr-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: "ENV"
            - name: SECRET_NAME
              value: ms-appsetting-srv-secret
      imagePullSecrets:
        - name: ecr-key
