apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsetting-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appsetting
  template:
    metadata:
      labels:
        app: appsetting
    spec:
      containers:
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: ENV
            value: "ENV"
          - name: SECRET_NAME
            value: ms-appsetting-srv-secret
      imagePullSecrets:
        - name: ecr-key
