apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/authservice-ecr-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: ENV
              value: "DEV"
            - name: SECRET_NAME
              value: ms-authservice-srv-secret
      imagePullSecrets:
        - name: ecr-key
