apiVersion: v1
kind: Service
metadata:
  name: authservice-service
  namespace: argocd
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 31247
  type: NodePort
