apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsetting-deployment
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: appsetting-ecr-repo
          env:
            - name: ENV
              value: "DEV"
            - name: SECRET_NAME
              value: ms-appsetting-devsrv-secret
