apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-appsetting-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-appsetting
  template:
    metadata:
      labels:
        app: dev-appsetting
    spec:
      containers:
        - name: dev-appsetting-ecr-repo
          image: 785059138812.dkr.ecr.ap-south-1.amazonaws.com/dev-appsetting-ecr-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "qa-dbsrv.cmjkuhgflwrj.ap-south-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "ZevoAdmin2024"
            - name: DB_PASSWORD
              value: "Zevo2024100"
            - name: DB_NAME
              value: "appsettingdb"
      imagePullSecrets:
        - name: ecr-key
