apiVersion: v1
kind: Service
metadata:
  name: dev-appsetting-service
  namespace: argocd
spec:
  selector:
    app: dev-appsetting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 6668
  type: NodePort
